name: Build Debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:   # 手动按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 6858069      # 7.0，schema 版本 2

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: 设置 Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
